package tryFunction;

public class exception {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
			int a = 40;
			int b = 0;
			int c = a/b ;
			
			System.out.println(" The output is: " + c);
		}
		catch(ArithmeticException e) {
			System.out.println("Division by zero not allowed!");
		}

	}

}
